name: Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod --dir . --site hasuda-syutudo-taisei --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
